# Generated by Django 4.2.7 on 2024-02-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('prepayment', models.FloatField(verbose_name='Предоплата')),
                ('debt', models.FloatField(verbose_name='Долг')),
                ('delivery_date_by_contract', models.DateField(verbose_name='Дата доставки по договору')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('customer_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Measurers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('metrics_date', models.DateField(verbose_name='Дата замера')),
                ('measurer', models.CharField(max_length=255, verbose_name='Замерщик')),
                ('contacts', models.CharField(max_length=255, verbose_name='Контакты')),
                ('comments', models.TextField(verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=255, verbose_name='Завод')),
                ('order_number', models.CharField(max_length=255, verbose_name='Номер заказа')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('payment', models.FloatField(verbose_name='Оплата')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки от завода')),
                ('square_meters', models.CharField(max_length=255, verbose_name='Квадратные мерты')),
                ('slopes', models.CharField(max_length=255, verbose_name='Откосы')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main_forms.contracts')),
            ],
        ),
        migrations.CreateModel(
            name='Installations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(verbose_name='Дата монтажа')),
                ('square_meters_price', models.FloatField(verbose_name='Стоимость квадратных метров')),
                ('linear_meters', models.FloatField(max_length=255, verbose_name='Кол-во м/п')),
                ('linear_meters_price', models.FloatField(verbose_name='Стоимость м/п')),
                ('additional_works', models.FloatField(verbose_name='Доп. работы')),
                ('total_amount', models.FloatField(verbose_name='Сумма')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='main_forms.contracts')),
            ],
        ),
        migrations.AddField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_forms.customers'),
        ),
    ]
