# Generated by Django 4.2.7 on 2023-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
