# Generated by Django 4.2.7 on 2023-11-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0002_contracts_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='montage_date',
        ),
    ]
