# Generated by Django 4.2.7 on 2023-11-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0003_remove_contracts_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installations',
            name='price_per_square_meter',
        ),
        migrations.RemoveField(
            model_name='installations',
            name='slopes',
        ),
        migrations.RemoveField(
            model_name='installations',
            name='square_meters_count',
        ),
        migrations.AddField(
            model_name='installations',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installations',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_forms.contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installations',
            name='linear_meters',
            field=models.FloatField(default=1, max_length=255, verbose_name='Кол-во м/п'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installations',
            name='linear_meters_price',
            field=models.FloatField(default=1, verbose_name='Стоимость м/п'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installations',
            name='square_meters',
            field=models.FloatField(default=1, max_length=255, verbose_name='Кол-во м2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installations',
            name='square_meters_price',
            field=models.FloatField(default=1, verbose_name='Стоимость м2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='debt',
            field=models.FloatField(verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='prepayment',
            field=models.FloatField(verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='installations',
            name='additional_works',
            field=models.FloatField(verbose_name='Доп. работы'),
        ),
        migrations.AlterField(
            model_name='installations',
            name='total_amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.FloatField(verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
