# Generated by Django 4.2.7 on 2023-11-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0004_remove_installations_price_per_square_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installations',
            name='address',
        ),
    ]
