# Generated by Django 4.2.7 on 2023-11-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0005_remove_installations_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installations',
            name='square_meters',
        ),
    ]
