# Generated by Django 4.2.7 on 2023-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0006_remove_installations_square_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='installations',
            name='square_meters_price',
            field=models.FloatField(verbose_name='Стоимость квадратных метров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='square_meters',
            field=models.CharField(max_length=255, verbose_name='Квадратные мерты'),
        ),
    ]
