# Generated by Django 4.2.7 on 2024-02-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0007_factories_alter_installations_square_meters_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_forms.contracts'),
        ),
    ]
