# Generated by Django 4.2.6 on 2023-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_forms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=255, verbose_name="Номер договора"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("factory", models.CharField(max_length=255, verbose_name="Завод")),
                (
                    "order_number",
                    models.CharField(max_length=255, verbose_name="Номер заказа"),
                ),
                ("price", models.IntegerField(verbose_name="Стоимость")),
                ("delivery_date", models.DateField(verbose_name="Дата доставки")),
                ("m2", models.CharField(max_length=255, verbose_name="м2")),
                ("slopes", models.CharField(max_length=255, verbose_name="Откосы")),
            ],
        ),
        migrations.AlterField(
            model_name="contracts",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="contract_number",
            field=models.CharField(max_length=255, verbose_name="Номер договора"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="customer",
            field=models.CharField(max_length=255, verbose_name="ФИО клиента"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="debt",
            field=models.IntegerField(verbose_name="Долг"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="delivery_date",
            field=models.DateField(verbose_name="Дата доставки"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="delivery_date_by_contract",
            field=models.DateField(verbose_name="Дата доставки по договору"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="montage_date",
            field=models.DateField(verbose_name="Дата монтажа"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="prepayment",
            field=models.IntegerField(verbose_name="Предоплата"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
    ]
