# Generated by Django 4.2.7 on 2023-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0002_orders_alter_contracts_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('customer', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contract_count', models.IntegerField(verbose_name='Кол-во договоров')),
                ('contract_cost', models.IntegerField(verbose_name='Стоимость договоров')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255, verbose_name='Номер договора')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('installation_date', models.DateField(verbose_name='Дата монтажа')),
                ('square_meters_count', models.CharField(max_length=255, verbose_name='Кол-во м2')),
                ('slopes', models.CharField(max_length=255, verbose_name='Откосы м/п')),
                ('price_per_square_meter', models.IntegerField(verbose_name='Стоимость м2')),
                ('additional_works', models.TextField(verbose_name='Доп. работы')),
                ('total_amount', models.IntegerField(verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('measurement_date', models.DateField(verbose_name='Дата замера')),
                ('contacts', models.CharField(max_length=255, verbose_name='Контакты')),
                ('comments', models.TextField(verbose_name='Комментарии')),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='m2',
            new_name='square_meters',
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата доставки от завода'),
        ),
    ]
