# Generated by Django 4.2.7 on 2023-11-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0003_customers_installation_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='contract_cost',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='contract_count',
        ),
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
