# Generated by Django 4.2.7 on 2023-11-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0004_remove_customers_contract_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_forms.customers'),
        ),
    ]
