# Generated by Django 4.2.7 on 2023-11-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_forms', '0005_remove_contracts_address_remove_contracts_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
